### ISSUE TITLE
Broken multiline support in State blocks

### ISSUE THREAD

**Issue by ZzZombo** [KaptainMicila/ZScript-VSCode#15]
https://github.com/PROPHESSOR/GZDoom-Extension-VSCode/issues/8

I've tried both of the currently known to me GZDoom editing extensions, and both do not look like they work anymore.

**Comment by KaptainMicila** [comment]
Hello, thanks for creating the issue.
I do suspect it's the newlines breaking stuff, as always.
Thanks to the example you've given, I'll investigate directly on that one.

**Comment by KaptainMicila** [comment]
Apologies for the confusion, I'll also copy my response from PHROPESSOR's fork on this issue (the one I can actually fix and not on another user's fork)

This is with VSCode's default "Dark" theme:

![dark](https://user-images.githubusercontent.com/50526449/222512718-9e739ec6-c262-4fe6-a845-8532c729bec7.png)

This is how it appears with VSCode's default "Light" theme:

![light](https://user-images.githubusercontent.com/50526449/222512731-4cc2814b-f9db-4001-aaba-b17e67ecfb3d.png)

**Comment by KaptainMicila** [comment]
This version of the extension does not handle autocompletion, only text highlighting (colored text).
If there's no issue with highlighting, I apologize: I can't fix other issues.

**Comment by KaptainMicila** [comment]
As it seems there's no issue, I'll be closing this one down.
