### ISSUE TITLE
ACS aliased to DECORATE language mode

### ISSUE THREAD

**Issue by AnomalousVixel** [KaptainMicila/ZScript-VSCode#20]
Is this intended?

**Comment by KaptainMicila** [comment]
Hi there, where is this happening?
May you send a screenshot of the issue, if possible?

**Comment by AnomalousVixel** [comment]
![image](https://github.com/user-attachments/assets/3ce77e91-059c-48c1-af52-3523b7af8706)

**Comment by KaptainMicila** [comment]
Oh, I see.
I'll fix it in the next version.
Thanks for noticing it.

**Comment by KaptainMicila** [comment]
I guess it worked the opposite: DECORATE was aliased to ACS, for some reason.
It was an easy fix and will be there in the next version.

**Comment by KaptainMicila** [comment]
Should be fixed now! GH-21
Please, comment if there are any issues!
